version: '3'

services:
  projectpath-pro:
    build: projectpath-pro
    ports:
      - "8080:8080"
    environment: 
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PLATFORM: ${DB_PLATFORM}
      SB_SECRET_KEY: ${SB_SECRET_KEY}
      TOKEN_EXPIRATION: ${TOKEN_EXPIRATION}
      REFRESH_TOKEN_EXPIRATION: ${REFRESH_TOKEN_EXPIRATION}
    restart: always
    depends_on:
      projectpath_db:
        condition: service_healthy
  projectpath_db:
    image: postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    healthcheck: 
      test: ["CMD", "pg_isready -U postgres"]
      timeout: 10s
      retries: 10